# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-08 11:58
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
