# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('event', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='categories',
            field=models.ManyToManyField(related_name='events', to='event.Category'),
        ),
    ]
